label: "Baseline WMT14"
description: "Baseline WMT14 model, exact same config as Bahdanau et al. 2014"

cell_size: 1000
attn_size: 1000
embedding_size: 620
bidir: True
cell_type: GRU

data_dir: data/WMT14
max_len: 50
model_dir: models/WMT14/baseline_legacy

steps_per_checkpoint: 10000
steps_per_eval: 10000
score_function: corpus_scores_bleu
keep_best: 1
max_to_keep: null

optimizer: adadelta
learning_rate: 1.0
batch_size: 80
batch_mode: standard
read_ahead: 20
max_gradient_norm: 1.0
max_epochs: 10

attention_type: global
final_state: last

weight_scale: 0.01

encoders:
  - name: en

decoders:
  - name: fr

generate_first: False
orthogonal_init: True
