label: "Baseline WMT14"
description: "Baseline WMT14 model with Adam"

cell_size: 1000
attn_size: 1000
embedding_size: 620
cell_type: GRU

data_dir: data/WMT14
max_len: 50
model_dir: models/WMT14/baseline
max_train_size: 1000000

steps_per_checkpoint: 10000
steps_per_eval: 10000
keep_best: 1
max_to_keep: 8

optimizer: adam
learning_rate: 0.0002
batch_size: 80
batch_mode: standard
read_ahead: 20
max_gradient_norm: 1.0
max_epochs: 5
learning_rate_decay_factor: 0.5
decay_every_n_epoch: 0.5

attention_type: global
final_state: last_both

weight_scale: 0.01

encoders:
  - name: en
    train_initial_states: True

decoders:
  - name: fr

generate_first: True
orthogonal_init: True
